"""Send the Inquisitor findings report via email.

Configuration (all via environment variables):

  INQUISITOR_REPORT_EMAIL   Recipient address (required to send email)
  INQUISITOR_FROM_EMAIL     Sender address  (default: inquisitor@heart-of-virtue.local)
  INQUISITOR_SMTP_HOST      SMTP server hostname (default: localhost)
  INQUISITOR_SMTP_PORT      SMTP server port     (default: 587)
  INQUISITOR_SMTP_USER      SMTP username        (optional)
  INQUISITOR_SMTP_PASSWORD  SMTP password        (optional)
  INQUISITOR_SMTP_TLS       Use STARTTLS: "1"=yes (default), "0"=no

If INQUISITOR_REPORT_EMAIL is not set, sending is silently skipped.
"""

import os
import smtplib
import socket
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from tools.inquisitor.reporter import AgentFinding, findings_to_bug_reports, BugSeverity


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _build_plain_body(findings: list, mode: str, layer: str) -> str:
    bugs = findings_to_bug_reports(findings)
    chapters = [f for f in findings if f.type == "chapter_complete"]
    stuck = [f for f in findings if f.type == "stuck"]

    lines = [
        "INQUISITOR REPORT",
        "=================",
        f"Mode:   {mode}",
        f"Layer:  {layer}",
        f"Bugs:   {len(bugs)} ({sum(1 for b in bugs if b.severity == BugSeverity.CRITICAL)} critical, "
        f"{sum(1 for b in bugs if b.severity == BugSeverity.HIGH)} high)",
        f"Chapters completed: {len(chapters)}",
        "",
    ]

    if chapters:
        lines.append("CHAPTERS COMPLETED")
        lines.append("------------------")
        for f in chapters:
            lines.append(f"  ✓ {f.chapter}: {f.title}")
            if f.description:
                lines.append(f"    {f.description[:200]}")
        lines.append("")

    if bugs:
        from tools.inquisitor.reporter import BugSeverity
        sev_order = [BugSeverity.CRITICAL, BugSeverity.HIGH, BugSeverity.MEDIUM, BugSeverity.LOW]
        for sev in sev_order:
            group = [b for b in bugs if b.severity == sev]
            if not group:
                continue
            lines.append(f"{sev.value.upper()} ({len(group)})")
            lines.append("-" * 40)
            for b in group:
                lines.append(f"  [{b.id}] {b.title}")
                lines.append(f"  Endpoint : {b.endpoint}")
                lines.append(f"  Actual   : {b.actual[:200]}")
                lines.append(f"  Triage   : {b.triage}")
                lines.append("")
    else:
        lines.append("No bugs found.")
        lines.append("")

    if stuck:
        lines.append("AGENT STUCK")
        lines.append("-----------")
        for f in stuck:
            lines.append(f"  {f.description[:300]}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by the Heart of Virtue Inquisitor harness.")
    return "\n".join(lines)


def _build_html_body(findings: list, mode: str, layer: str) -> str:
    bugs = findings_to_bug_reports(findings)
    chapters = [f for f in findings if f.type == "chapter_complete"]
    n_critical = sum(1 for b in bugs if b.severity == BugSeverity.CRITICAL)
    n_high = sum(1 for b in bugs if b.severity == BugSeverity.HIGH)

    colour = "#d32f2f" if n_critical else "#f57c00" if n_high else "#388e3c"

    rows = ""
    for b in bugs:
        sev_colour = {
            "critical": "#d32f2f", "high": "#f57c00",
            "medium": "#1565c0", "low": "#555",
        }.get(b.severity.value if hasattr(b.severity, "value") else str(b.severity), "#555")
        rows += (
            f"<tr>"
            f"<td style='color:{sev_colour};font-weight:bold'>{b.severity.value.upper()}</td>"
            f"<td><code>{b.id}</code></td>"
            f"<td>{b.title}</td>"
            f"<td><code>{b.endpoint}</code></td>"
            f"<td>{b.triage}</td>"
            f"</tr>"
        )

    chapter_rows = "".join(
        f"<tr><td>✓</td><td><b>{f.chapter}</b></td><td>{f.description[:200]}</td></tr>"
        for f in chapters
    )

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
body{{font-family:monospace;background:#0a0a0a;color:#ccc;padding:20px}}
h1{{color:#00FF00}}h2{{color:#00FFFF}}
table{{border-collapse:collapse;width:100%}}
th,td{{border:1px solid #333;padding:6px 10px;text-align:left}}
th{{background:#1a1a1a;color:#00FFFF}}
</style></head>
<body>
<h1>Inquisitor Report</h1>
<p>Mode: <b>{mode}</b> &nbsp;|&nbsp; Layer: <b>{layer}</b></p>
<p style="color:{colour}">
  {len(bugs)} bug(s) found &mdash; {n_critical} critical, {n_high} high
</p>

{"<h2>Chapters Completed</h2><table><tr><th></th><th>Chapter</th><th>Notes</th></tr>" + chapter_rows + "</table>" if chapters else ""}

{"<h2>Bugs</h2><table><tr><th>Severity</th><th>ID</th><th>Title</th><th>Endpoint</th><th>Triage</th></tr>" + rows + "</table>" if bugs else "<h2>Bugs</h2><p>None found.</p>"}

<hr><p style="color:#555;font-size:0.85em">Generated by Heart of Virtue Inquisitor</p>
</body></html>"""


def send_report(
    findings: list,
    mode: str,
    layer: str,
    output_path: Optional[str] = None,
) -> bool:
    """Send the Inquisitor report by email if INQUISITOR_REPORT_EMAIL is set.

    Returns True if the email was sent, False if skipped or failed.
    """
    recipient = _env("INQUISITOR_REPORT_EMAIL")
    if not recipient:
        return False

    bugs = findings_to_bug_reports(findings)
    n_critical = sum(1 for b in bugs if b.severity == BugSeverity.CRITICAL)
    n_high = sum(1 for b in bugs if b.severity == BugSeverity.HIGH)
    subject = (
        f"Inquisitor [{mode}] — {len(bugs)} bug(s) "
        f"({n_critical} critical, {n_high} high)"
    )

    sender = _env("INQUISITOR_FROM_EMAIL", "inquisitor@heart-of-virtue.local")
    plain = _build_plain_body(findings, mode, layer)
    html = _build_html_body(findings, mode, layer)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    # Attach JSON report if available
    if output_path:
        try:
            import json as _json
            from email.mime.application import MIMEApplication
            with open(output_path, "rb") as fh:
                attachment = MIMEApplication(fh.read(), _subtype="json")
                attachment.add_header(
                    "Content-Disposition", "attachment",
                    filename="inquisitor_findings.json",
                )
                msg.attach(attachment)
        except Exception:
            pass

    smtp_host = _env("INQUISITOR_SMTP_HOST", "localhost")
    smtp_port = int(_env("INQUISITOR_SMTP_PORT", "587"))
    smtp_user = _env("INQUISITOR_SMTP_USER")
    smtp_password = _env("INQUISITOR_SMTP_PASSWORD")
    use_tls = _env("INQUISITOR_SMTP_TLS", "1") != "0"

    try:
        if use_tls:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
            server.ehlo()
            server.starttls()
            server.ehlo()
        else:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)

        if smtp_user and smtp_password:
            server.login(smtp_user, smtp_password)

        server.sendmail(sender, [recipient], msg.as_string())
        server.quit()
        print(f"[inquisitor] Report emailed to {recipient}")
        return True

    except (smtplib.SMTPException, socket.error, OSError) as exc:
        print(f"[inquisitor] Warning: could not send email — {exc}")
        return False
