// AUTO-GENERATED by scripts/generate-sfx-durations.mjs — do not edit by hand.
// Natural (1x) playback length in ms of each shipped sfx_<cue>.wav, read from
// the WAV header. Regenerate after changing audio: `npm run sfx:durations`.
// See docs/development/combat-streaming-plan.md (issue #436).

export const SFX_DURATIONS = {
  "attack": 100,
  "attack_hit": 150,
  "attack_miss": 250,
  "attack_parry": 200,
  "attack_swipe": 200,
  "click": 55,
  "combat_start": 730,
  "enemy_death": 800,
  "error": 300,
  "heal": 600,
  "item_use": 250,
  "level_up": 770,
  "low_health_warning": 330,
  "move": 80,
  "player_death": 1800,
  "quest_complete": 770,
  "status_hit": 220,
  "ui_confirm": 180,
};
