#!/usr/bin/env python
"""Acceptance test generator for Heart of Virtue features.

Generates minimal test infrastructure (maps, scenarios, config files, scripts)
for rapid feature validation. Integrates with the bug-hunt harness and browser
testing (gstack /qa).

Usage:
    python tools/acceptance_test_generator.py \
        --feature "cooldown drain on passive moves" \
        --output tests/acceptance/cooldown-passive
"""

import argparse
import json
import textwrap
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "src"


class TestArtifact:
    """Represents a single generated test artifact (file to write)."""

    def __init__(self, path: Path, content: str, description: str = ""):
        self.path = path
        self.content = content
        self.description = description

    def write(self) -> None:
        """Write the artifact to disk."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(self.content)
        print(f"  ✓ {self.path.relative_to(ROOT)} — {self.description}")


class AcceptanceTestMapBuilder:
    """Generates minimal test maps (2 tiles) for feature testing."""

    def __init__(self, feature_name: str, feature_desc: str):
        self.feature_name = feature_name
        self.feature_desc = feature_desc

    def build(self) -> dict:
        """Return a minimal test map (JSON-serializable dict)."""
        # Simple 2x2 grid: staging area + test arena
        return {
            "metadata": {
                "bgm": "dream_space",
                "theme": f"Feature test: {self.feature_name}",
            },
            "(0, 0)": {
                "id": "tile_staging",
                "title": "Test Staging Area",
                "description": "A blank chamber used for feature testing. It is quiet and empty, save for a single glowing marker on the floor.",
                "exits": ["east"],
                "block_exit": [],
                "events": [],
                "items": [],
                "npcs": [],
                "objects": [],
            },
            "(1, 0)": {
                "id": "tile_arena",
                "title": "Test Arena",
                "description": "A small arena configured for testing. The walls are bare stone; the floor is marked with a test grid.",
                "exits": ["west"],
                "block_exit": [],
                "events": [],
                "items": [],
                "npcs": [],
                "objects": [],
            },
        }


class AcceptanceTestScenarioBuilder:
    """Generates scenario classes (Python code) for integration with bug-hunt harness."""

    def __init__(self, feature_name: str, feature_desc: str):
        self.feature_name = feature_name
        self.feature_desc = feature_desc
        # Convert to snake_case class name (e.g., "cooldown drain" → "CooldownDrain")
        self.class_name = "".join(w.capitalize() for w in feature_name.split()).replace("-", "")
        self.scenario_name = feature_name.lower().replace(" ", "_").replace("-", "_")

    def build(self) -> str:
        """Return Python scenario code as a string."""
        return textwrap.dedent(f'''\
            """Acceptance test scenario for: {self.feature_name}

            Feature: {self.feature_desc}

            This scenario is auto-generated by the acceptance-test skill.
            Customize the run() method to add your assertions.
            """

            from typing import List
            from .base import Scenario
            from ..client import GameClient
            from ..reporter import BugReport, BugSeverity, BugCategory


            class {self.class_name}Scenario(Scenario):
                name = "{self.scenario_name}"
                description = "{self.feature_desc}"

                def run(self, client: GameClient) -> List[BugReport]:
                    """Test the feature and return any bugs found.

                    TODO: Add your feature-specific assertions here.
                    The test map is already configured and Jean is spawned on (0, 0).
                    """
                    bugs = []

                    # Verify basic game state
                    resp = client.get("/api/game/status")
                    bug = self._check_status(
                        resp, 200, "/api/game/status", "GET", "Game status"
                    )
                    if bug:
                        bugs.append(bug)

                    # TODO: Add feature-specific checks below
                    # Example:
                    #   resp = client.post("/api/combat/move", json={{"move_id": "SomeMove"}})
                    #   if resp.status_code != 200:
                    #       bugs.append(self._bug(...))

                    return bugs
            ''')


class AcceptanceTestConfigBuilder:
    """Generates config INI files for test execution."""

    def __init__(self, feature_name: str, test_map_name: str):
        self.feature_name = feature_name
        self.test_map_name = test_map_name
        self.config_name = feature_name.lower().replace(" ", "_").replace("-", "_")

    def build(self) -> str:
        """Return INI config content as a string."""
        return textwrap.dedent(f'''\
            # =============================================================================
            # Acceptance Test Config: {self.feature_name}
            # =============================================================================
            # Auto-generated by the acceptance-test skill.
            # Edit this file to customize the test environment, then re-run.
            # =============================================================================

            [game]
            testmode            = True
            skipdialog          = True
            skipintro           = True
            startmap            = {self.test_map_name}
            startposition       = 0, 0
            use_colour          = True
            enable_animations   = True
            learn_all_skills    = True

            # =============================================================================
            # [player]  — Jean's starting state
            # =============================================================================
            [player]

            hp              = 100
            maxhp           = 100

            strength        = 10
            finesse         = 10
            speed           = 10
            endurance       = 10
            charisma        = 10
            intelligence    = 10
            faith           = 10

            level           = 1
            exp             = 0
            heat            = 1.0
            starting_items  = Shortsword, LeatherArmor, Restorative, Restorative

            # =============================================================================
            # [scenario]  — Test execution parameters
            # =============================================================================
            [scenario]

            active_scenario = acceptance_test
            max_rounds      = 50
            spawn_ally      = False
            custom_enemies  =

            # =============================================================================
            # [debug]
            # =============================================================================
            [debug]

            debug_mode              = True
            debug_positions         = False
            debug_damage_calc       = False
            debug_accuracy          = False
            debug_ai_decisions      = False
            debug_npc_positions     = False

            log_combat_moves        = False
            log_distance_calculations = False
            log_npc_decisions       = False
            log_file                = acceptance_test.log

            monitor_bps             = False
            log_performance         = False

            # =============================================================================
            # [arena]
            # =============================================================================
            [arena]

            coordinate_grid_size        = 50, 50
            validate_grid_bounds        = True
            validate_distance_calc      = True
            validate_angle_calc         = True
            validate_modifier_calc      = True

            show_combat_distance        = False
            show_unit_positions         = False
            show_facing_directions      = False
            show_damage_modifiers       = False
            show_accuracy_modifiers     = False
            show_coordinate_display     = False

            standard_player_x           = 25
            standard_player_y           = 10
            standard_enemy_x            = 25
            standard_enemy_y            = 40

            # =============================================================================
            # [npc_ai]
            # =============================================================================
            [npc_ai]

            ai_difficulty               = 3
            npc_decision_delay          = 0.5
            npc_flanking_enabled        = True
            npc_flanking_threshold      = 45.0
            npc_retreat_health_threshold = 0.3
            npc_flanking_distance_range = 20.0 to 40.0
            npc_tactical_retreat        = True

            # =============================================================================
            # [development]
            # =============================================================================
            [development]

            god_mode        = False
            skip_combat     = False
            enable_hot_reload = False
            ''')


class AcceptanceTestScriptBuilder:
    """Generates shell scripts for running acceptance tests."""

    def __init__(self, feature_name: str, config_name: str, scenario_name: str):
        self.feature_name = feature_name
        self.config_name = config_name
        self.scenario_name = scenario_name

    def build_runner_script(self) -> str:
        """Return a shell script that runs the acceptance test."""
        return textwrap.dedent(f'''\
            #!/bin/bash
            # Acceptance Test Runner: {self.feature_name}
            # Auto-generated by the acceptance-test skill.
            #
            # Usage:
            #   ./run.sh              # Run with bug-hunt harness (fast, in-process)
            #   ./run.sh --browser    # Run with gstack /qa (browser-based, full UI testing)

            set -e

            SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" && pwd )"
            ROOT_DIR="$SCRIPT_DIR/../.."
            CONFIG_FILE="$SCRIPT_DIR/config.ini"

            echo "[acceptance-test] Running: {self.feature_name}"
            echo "[acceptance-test] Config: $CONFIG_FILE"

            if [[ "$1" == "--browser" ]]; then
                echo "[acceptance-test] Starting local servers..."
                cd "$ROOT_DIR"

                # Start API server in background
                CONFIG_FILE="$CONFIG_FILE" python tools/run_api.py &
                API_PID=$!

                # Wait for API to be ready
                sleep 2

                # Start frontend dev server in background
                cd "$ROOT_DIR/frontend"
                npm run dev &
                FRONTEND_PID=$!

                # Wait for frontend
                sleep 3

                echo "[acceptance-test] Servers ready. Starting gstack /qa..."
                cd "$ROOT_DIR"

                # Run browser tests via gstack
                # (This would be: gstack /qa <test-plan-json>)
                echo "[acceptance-test] Browser testing would go here (gstack /qa)"

                # Cleanup
                kill $API_PID $FRONTEND_PID 2>/dev/null || true
            else
                # Default: run via bug-hunt harness (in-process, fast)
                cd "$ROOT_DIR"
                CONFIG_FILE="$CONFIG_FILE" python tools/bug_hunt.py --scenario {self.scenario_name}
            fi
            ''')

    def build_plan_json(self) -> str:
        """Return a gstack test plan JSON for browser-based testing."""
        plan = {
            "name": f"Acceptance Test: {self.feature_name}",
            "description": f"Feature validation for {self.feature_name}",
            "steps": [
                {
                    "action": "navigate",
                    "target": "http://localhost:3000",
                    "description": "Navigate to game homepage",
                },
                {
                    "action": "login",
                    "description": "Log in as test user",
                },
                {
                    "action": "start_game",
                    "map": "acceptance-test-map",
                    "description": "Start game on test map",
                },
                {
                    "action": "verify",
                    "target": "#game-container",
                    "description": "Verify game loaded successfully",
                    "assertion": "visible",
                },
                {
                    "action": "custom",
                    "script": "// TODO: Add feature-specific test steps",
                    "description": "Feature-specific validation",
                },
            ],
        }
        return json.dumps(plan, indent=2)


class AcceptanceTestGenerator:
    """Main orchestrator for acceptance test generation."""

    def __init__(self, feature_name: str, feature_desc: str, output_dir: Path):
        self.feature_name = feature_name
        self.feature_desc = feature_desc
        self.output_dir = output_dir.resolve()

        # Derived names
        self.map_name = feature_name.lower().replace(" ", "_").replace("-", "_")
        self.scenario_name = self.map_name
        self.config_name = self.map_name

    def generate(self) -> list[TestArtifact]:
        """Generate all test artifacts and return them."""
        artifacts = []

        # 1. Test map (JSON)
        map_builder = AcceptanceTestMapBuilder(self.feature_name, self.feature_desc)
        map_content = json.dumps(map_builder.build(), indent=2)
        map_path = SRC_DIR / "resources" / "maps" / f"acceptance-test-{self.map_name}.json"
        artifacts.append(TestArtifact(
            map_path,
            map_content,
            "Minimal test map (2-tile arena)"
        ))

        # 2. Scenario class (Python)
        scenario_builder = AcceptanceTestScenarioBuilder(
            self.feature_name,
            self.feature_desc
        )
        scenario_path = Path(ROOT) / "tools" / "harness" / "scenarios" / f"acceptance_test_{self.scenario_name}.py"
        artifacts.append(TestArtifact(
            scenario_path,
            scenario_builder.build(),
            "Scenario class (extends harness.scenarios.Scenario)"
        ))

        # 3. Config INI file
        config_builder = AcceptanceTestConfigBuilder(
            self.feature_name,
            f"acceptance-test-{self.map_name}"
        )
        config_path = self.output_dir / "config.ini"
        artifacts.append(TestArtifact(
            config_path,
            config_builder.build(),
            "Game configuration (test parameters)"
        ))

        # 4. Runner script (bash)
        script_builder = AcceptanceTestScriptBuilder(
            self.feature_name,
            self.config_name,
            self.scenario_name
        )
        script_path = self.output_dir / "run.sh"
        artifacts.append(TestArtifact(
            script_path,
            script_builder.build_runner_script(),
            "Runner script (bash, in-process & browser modes)"
        ))

        # 5. Test plan JSON (for gstack)
        plan_path = self.output_dir / "test_plan.json"
        artifacts.append(TestArtifact(
            plan_path,
            script_builder.build_plan_json(),
            "Browser test plan (gstack /qa)"
        ))

        # 6. README (usage guide)
        readme_content = textwrap.dedent(f'''\
            # Acceptance Test: {self.feature_name}

            Auto-generated test suite for validating {self.feature_name}.

            ## Files

            - **config.ini** — Game configuration for the test (player stats, starting map, debug flags)
            - **run.sh** — Main test runner script
            - **test_plan.json** — Browser-based test plan for gstack /qa
            - **acceptance-test-{self.map_name}.json** — Test map (in src/resources/maps/)

            ## Running the Test

            ### Option 1: In-process (fast, no servers needed)
            ```bash
            cd {self.output_dir.relative_to(ROOT)}
            ./run.sh
            ```

            This uses the bug-hunt harness to run the scenario in-process via Flask test client.
            Output: Console report with any bugs found.

            ### Option 2: Browser-based (full UI testing via gstack)
            ```bash
            cd {self.output_dir.relative_to(ROOT)}
            ./run.sh --browser
            ```

            This starts the API and frontend servers, then runs the test plan via gstack /qa.
            Output: Browser screenshots, JS console errors, rendering issues.

            ### Option 3: Manual testing
            ```bash
            cd {ROOT}
            CONFIG_FILE={self.output_dir.relative_to(ROOT)}/config.ini python tools/run_api.py

            # In another terminal:
            cd {ROOT}/frontend
            npm run dev

            # Then open http://localhost:3000 and test manually
            ```

            ## Customization

            Edit **config.ini** to adjust:
            - Player starting stats (hp, strength, finesse, etc.)
            - Debug logging flags
            - NPC AI difficulty
            - Arena grid size

            Edit **config.ini**'s `[game]` section to change `startmap` if needed.

            Edit the scenario class (tools/harness/scenarios/acceptance_test_{self.scenario_name}.py)
            to add feature-specific assertions in the `run()` method.

            ## Integration

            Once the scenario is tested and working, register it in:
            **tools/harness/scenarios/__init__.py**

            Add:
            ```python
            from .acceptance_test_{self.scenario_name} import {scenario_builder.class_name}Scenario
            ...
            _ALL_SCENARIOS = [
                ...
                {scenario_builder.class_name}Scenario(),
            ]
            ```

            Then it becomes part of the standard bug-hunt harness:
            ```bash
            python tools/bug_hunt.py --scenario {self.scenario_name}
            python tools/bug_hunt.py --headless --output bugs.json
            ```
            ''')
        artifacts.append(TestArtifact(
            self.output_dir / "README.md",
            readme_content,
            "Usage guide and customization instructions"
        ))

        return artifacts


def main():
    parser = argparse.ArgumentParser(
        description="Generate acceptance test infrastructure for Heart of Virtue features."
    )
    parser.add_argument(
        "--feature",
        required=True,
        help="Feature name/description (e.g., 'cooldown drain on passive moves')"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory (default: tests/acceptance/<feature-name>)"
    )

    args = parser.parse_args()

    # Determine output directory
    if args.output:
        output_dir = Path(args.output)
    else:
        feature_slug = args.feature.lower().replace(" ", "-").replace("_", "-")
        output_dir = ROOT / "tests" / "acceptance" / feature_slug

    print(f"\n[acceptance-test] Generating test suite for: {args.feature}")
    print(f"[acceptance-test] Output directory: {output_dir.relative_to(ROOT)}\n")

    generator = AcceptanceTestGenerator(
        args.feature,
        args.feature,
        output_dir
    )

    artifacts = generator.generate()

    print("Generated artifacts:")
    for artifact in artifacts:
        artifact.write()

    # Make the runner script executable
    runner_script = output_dir / "run.sh"
    if runner_script.exists():
        runner_script.chmod(0o755)
        print(f"  ✓ {runner_script.relative_to(ROOT)} — made executable")

    print(f"\n[acceptance-test] ✓ Done!")
    print(f"[acceptance-test] Next steps:")
    print(f"[acceptance-test]   1. Review the generated files in {output_dir.relative_to(ROOT)}/")
    print(f"[acceptance-test]   2. Run: cd {output_dir.relative_to(ROOT)} && ./run.sh")
    print(f"[acceptance-test]   3. Customize config.ini and the scenario class as needed")
    print(f"[acceptance-test]   4. Register the scenario in tools/harness/scenarios/__init__.py")
    print()


if __name__ == "__main__":
    main()
