#!/usr/bin/env python3
"""Regenerate the save-deserialization class-inventory manifest (issue #13, Phase 4).

``src.secure_pickle.get_allowlist()`` introspects the engine modules and returns
the concrete set of engine classes, so it never drifts behind the code at
runtime. This script materializes that set to a sorted, human-diffable manifest
so the drift is also visible in review, and so ``test_secure_pickle`` can assert
the checked-in file still matches the code.

What this manifest is **not**: the enforcement gate. Nothing on the save-load
path consults ``get_allowlist()`` -- ``secure_pickle._build_allowlist``'s own
docstring says so. Strict-mode enforcement is the broader engine-module rule in
``_is_allowed`` (which also admits engine functions and methods, not just
classes), and it only runs at all when ``HOV_STRICT_UNPICKLE`` is set. Calling
this file "the strict-mode allow-list" -- as this docstring once did -- reads as
a promise the loader does not make. The same disclaimer is written into the
generated JSON as a ``note`` key so the artifact carries its own caveat.

Usage:
    python tools/gen_allowlist_manifest.py            # write the manifest
    python tools/gen_allowlist_manifest.py --check    # exit 1 if out of date
"""

import os
import sys
import json
import argparse

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import secure_pickle  # noqa: E402

# Travels with the artifact: a reader who opens the JSON without opening this
# script must not conclude the file gates anything.
MANIFEST_NOTE = (
    "Inventory of engine classes for drift detection, generated by "
    "tools/gen_allowlist_manifest.py. NOT the enforcement gate: nothing on the "
    "save-load path consults secure_pickle.get_allowlist(). Strict-mode "
    "enforcement is secure_pickle._is_allowed (engine-module based, admits "
    "functions and methods too) and runs only when HOV_STRICT_UNPICKLE is set, "
    "which no config, .env.example or CI workflow does. Regenerate, never "
    "hand-edit."
)

MANIFEST_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs", "development", "save-allowlist-manifest.json",
)


def build_manifest():
    """Return the current allow-list as a sorted, JSON-serializable manifest."""
    entries = [
        {"module": module, "name": name}
        for module, name in sorted(secure_pickle.get_allowlist())
    ]
    return {
        "note": MANIFEST_NOTE,
        "header_version": secure_pickle.HEADER_VERSION,
        "count": len(entries),
        "classes": entries,
    }


def _serialize(manifest):
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if the manifest on disk is out of date.",
    )
    args = parser.parse_args(argv)

    manifest_text = _serialize(build_manifest())

    if args.check:
        if not os.path.exists(MANIFEST_PATH):
            print(f"Manifest missing: {MANIFEST_PATH}", file=sys.stderr)
            return 1
        with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
            current = f.read()
        if current != manifest_text:
            print(
                "Allow-list manifest is out of date. Run "
                "`python tools/gen_allowlist_manifest.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("Allow-list manifest is up to date.")
        return 0

    os.makedirs(os.path.dirname(MANIFEST_PATH), exist_ok=True)
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        f.write(manifest_text)
    print(f"Wrote {MANIFEST_PATH} ({build_manifest()['count']} classes).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
