__author__ = "Alex Egbert"

import src.functions as functions
import src.secure_pickle as secure_pickle
import json
import inspect
import importlib
from pathlib import Path
from typing import Final
from src.scenario_config import ScenarioConfig
from src.coordinate_config import CoordinateSystemConfig
from src.narration import narrate

RESOURCES_DIR: Final = Path(__file__).parent / "resources"

# Depth cap for map-instance deserialization. Map JSON is attacker-influenceable
# (map files can be hand-edited or shipped by third parties), so a deeply nested
# or recursion-bomb ``props`` graph must not blow the Python stack. Real maps
# nest only a handful of levels; this leaves generous headroom.
MAX_DESERIALIZE_DEPTH: Final = 100


def tile_exists(map_to_check, x, y):
    """Returns the tile at the given coordinates or None if there is no tile.
    :param map_to_check: the dictionary object containing the tile
    :param x: the x-coordinate in the worldspace
    :param y: the y-coordinate in the worldspace
    :return: the tile at the given coordinates or None if there is no tile
    """
    return map_to_check.get((x, y))


class Universe:  # "globals" for the game state can be stored here, as well as all the maps
    def __init__(self, player=None):
        self.player = player
        self.game_tick = 0
        self.maps = []
        self.starting_map_default = None
        self.story = {  # global switches and variables.
            # Putting them in a dict will make it easier to change on the fly while debugging
            "gorran_first": "0",
            # Gorran language acquisition arc. Values: "0"–"4" matching narrative stages.
            # Stage 0 — no words (all gesture/sound).
            # Stage 1 — "Stop" (first word, emergency, set by Ch01GorranFirstWord event).
            # Stage 2 — single-word directions (here/there/wait/good/no/name).
            # Stage 3 — short phrases, physical vocabulary for emotion.
            # Stage 4 — effortful sentences; the crisis scene.
            "gorran_language_stage": "0",
        }
        self.locked_chests = []
        self.testing_mode = False  # test mode flag from config
        self.game_config = None  # full GameConfig object for access to all settings
        self.scenario_config = None  # ScenarioConfig for combat scenario management
        self.coordinate_config = None  # CoordinateSystemConfig for grid positioning

    def get_tile(self, x, y):
        """Get tile at coordinates from the current player's map."""
        if self.player and self.player.map:
            return tile_exists(self.player.map, x, y)
        return None

    def build(
        self, player
    ):  # builds all the maps as they are, then loads them into self.maps
        # Ensure universe has a reference to the active player BEFORE loading maps so deserialization can inject it
        self.player = player

        # Initialize config systems if player has game_config
        if hasattr(player, "game_config") and player.game_config:
            self.scenario_config = ScenarioConfig(player)
            self.coordinate_config = CoordinateSystemConfig(player)

        if player.saveuniv is not None and player.savestat is not None:
            self.maps = player.saveuniv
        else:  # new game
            # First load any JSON maps generated by map_generator (preferred modern format)
            self._load_all_json_maps(player)
            # determine starting map
            for location in self.maps:
                if "start" in location["name"] and self.starting_map_default is None:
                    self.starting_map_default = location

    # ---------------- JSON MAP SUPPORT -----------------
    def _json_maps_root_candidates(self):
        """Return candidate directories that may contain json map files."""
        candidates = []
        # primary resources/maps under src/resources
        maps_dir = RESOURCES_DIR / "maps"
        candidates.append(maps_dir)
        # also accept utils/src/resources/maps (where the editor saves by default)
        utils_variant = (
            Path(__file__).parent.parent / "utils" / "src" / "resources" / "maps"
        )
        candidates.append(utils_variant)
        return [c for c in candidates if c.exists()]

    def _load_all_json_maps(self, player):
        loaded = 0
        for root in self._json_maps_root_candidates():
            for jf in sorted(root.glob("*.json")):
                try:
                    self._load_single_json_map(player, jf)
                    loaded += 1
                except Exception as e:
                    narrate(f"ERROR: Failed to load map from {jf}: {e}")
        return loaded

    @staticmethod
    def _deserialize_class_allowed(mod_name, cls_name):
        """Gate a map-JSON ``module:class`` reference against the engine trust
        boundary shared with pickle deserialization (``src.secure_pickle``).

        Map JSON is attacker-influenceable, so a hostile ``__module__`` /
        ``__class_type__`` must not let the loader import an arbitrary module or
        resolve a dangerous global (``os.system``, ``subprocess.Popen``, ...).
        Only engine modules and a curated safe-stdlib set are permitted; the same
        gate that guards save-file unpickling. ``mod_name`` is the *canonical*
        (``src.*``) module path.
        """
        if not isinstance(mod_name, str) or not isinstance(cls_name, str):
            return False
        return secure_pickle._is_allowed(mod_name, cls_name)

    def _deserialize_saved_instance(self, payload, _depth=0):
        """Deserialize an instance saved by map_generator (class+module+props). Returns object or None."""
        # Depth-bound the recursion so a nested/cyclic-looking props graph in a
        # hostile map cannot overflow the Python stack (returns None instead).
        if _depth > MAX_DESERIALIZE_DEPTH:
            narrate("ERROR: map deserialization exceeded maximum nesting depth")
            return None
        # Recursively deserialize nested objects in props, events, etc.
        # Support class-type markers emitted by the map editor (e.g. {'__class_type__': 'items:Item'})
        if isinstance(payload, dict) and "__class_type__" in payload:
            spec = payload.get("__class_type__")
            try:
                mod_name, cls_name = spec.rsplit(":", 1)
                if mod_name and cls_name:
                    # Map data stores bare module names; import the canonical
                    # src.* module so classes match the running engine's.
                    canonical = functions.canonical_module_name(mod_name)
                    if not self._deserialize_class_allowed(canonical, cls_name):
                        narrate(
                            f"ERROR: refusing to resolve non-engine class type '{spec}'"
                        )
                        return None
                    module = importlib.import_module(canonical)
                    return getattr(module, cls_name)
            except Exception as e:
                narrate(f"ERROR: Failed to resolve class type '{spec}': {e}")
                return None

        if not isinstance(payload, dict) or "__class__" not in payload:
            return None
        cls_name = payload.get("__class__")
        mod_name = payload.get("__module__")
        props = payload.get("props") or {}

        if not mod_name or not isinstance(mod_name, str):
            return None
        if not cls_name or not isinstance(cls_name, str):
            return None
        if not isinstance(props, dict):
            return None

        # Throw error if mod name has improper format; 'src.' prefix should not be present.
        if mod_name.startswith("src."):
            raise ValueError(f"Invalid module name format: {mod_name}")

        # Gate against the shared engine trust boundary before importing anything.
        # A hostile __module__ (os, subprocess, a malformed dotted path, ...) is
        # rejected here rather than reaching importlib/getattr.
        canonical = functions.canonical_module_name(mod_name)
        if not self._deserialize_class_allowed(canonical, cls_name):
            narrate(
                f"ERROR: refusing to deserialize non-engine class "
                f"'{mod_name}.{cls_name}'"
            )
            return None

        def recursive_deserialize(value, depth):
            if depth > MAX_DESERIALIZE_DEPTH:
                return None
            if isinstance(value, dict):
                if "__class__" in value and "__module__" in value:
                    return self._deserialize_saved_instance(value, _depth=depth + 1)
                elif "__class_type__" in value:
                    return self._deserialize_saved_instance(value, _depth=depth + 1)
                else:
                    # Recursively check all dict values
                    return {
                        k: recursive_deserialize(v, depth + 1)
                        for k, v in value.items()
                    }
            elif isinstance(value, list):
                return [recursive_deserialize(v, depth + 1) for v in value]
            else:
                return value

        # Recursively deserialize all props
        props = {
            k: recursive_deserialize(v, _depth + 1) for k, v in props.items()
        }

        try:
            # Map data stores bare module names (validated + gated above); import
            # the canonical src.* module so classes match the running engine's.
            module = importlib.import_module(canonical)
            cls = getattr(module, cls_name)
            # Try to supply only parameters accepted by __init__ (excluding self)
            try:
                sig = inspect.signature(cls.__init__)
                pnames = [p.name for p in sig.parameters.values() if p.name != "self"]
                init_kwargs = {k: v for k, v in props.items() if k in pnames}
                # If 'player' is a parameter, pass self.player
                if "player" in pnames and "player" not in init_kwargs:
                    init_kwargs["player"] = self.player
                inst = cls(**init_kwargs)
            except Exception:
                inst = cls.__new__(cls)
                try:
                    cls.__init__(inst)  # type: ignore
                except Exception:
                    pass
            # Apply remaining props as attributes
            for k, v in props.items():
                try:
                    # Skip setting player or tile if they're null - let runtime set these
                    if k in ("player", "tile") and v is None:
                        continue
                    if (
                        k == "inventory"
                        and hasattr(inst, "inventory")
                        and getattr(inst, "inventory")
                        and isinstance(v, list)
                        and len(v) == 0
                    ):
                        continue
                    setattr(inst, k, v)
                except Exception:
                    pass
            return inst
        except Exception as e:
            narrate(f"ERROR: Failed to deserialize '{mod_name}.{cls_name}': {e}")
            return None

    def _load_single_json_map(self, player, json_path: Path):
        with open(json_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        map_name = json_path.stem
        this_map: dict = {"name": map_name}
        # iterate coordinate keys
        for coord_str, tile_data in raw.items():
            if coord_str == "metadata":
                this_map["metadata"] = tile_data
                continue
            try:
                x_str, y_str = coord_str.strip("()").split(",")
                x = int(x_str)
                y = int(y_str)
            except Exception:
                continue
            # determine tile class name from title; fallback to generic MapTile if not found
            title = tile_data.get("title") or tile_data.get("id") or f"tile_{x}_{y}"
            description = tile_data.get("description", "")
            try:
                tile_cls = functions.seek_class(title, "tilesets", allow_other_modules=False)
            except ValueError as e:
                narrate(
                    f"ERROR: Failed to resolve tile class for title '{title}' "
                    f"at {coord_str} in map '{map_name}': {e}; falling back to MapTile"
                )
                from src.tiles import MapTile as tile_cls  # fallback
            tile_instance = tile_cls(self, this_map, x, y)
            # Store tile name from JSON title; only if the class didn't set its own.
            # MapTile.__init__ never sets self.name, so getattr returns None for generic tiles.
            if not getattr(tile_instance, "name", None):
                tile_instance.name = title
            # Override description from JSON only if one was provided (tile subclasses
            # may hardcode their own description via super().__init__; respect that as default)
            if description:
                tile_instance.description = description
            # block exits & symbol
            if "block_exit" in tile_data and isinstance(tile_data["block_exit"], list):
                tile_instance.block_exit = list(tile_data["block_exit"])
            # exits whitelist: if the JSON specifies allowed exits, block every other direction
            _all_dirs = {
                "north",
                "south",
                "east",
                "west",
                "northeast",
                "northwest",
                "southeast",
                "southwest",
            }
            if "exits" in tile_data and isinstance(tile_data["exits"], list):
                allowed = set(tile_data["exits"])
                for _dir in _all_dirs - allowed:
                    if _dir not in tile_instance.block_exit:
                        tile_instance.block_exit.append(_dir)
            if "symbol" in tile_data and hasattr(tile_instance, "symbol"):
                try:
                    tile_instance.symbol = tile_data["symbol"]
                except Exception:
                    pass
            # events
            for ev_payload in tile_data.get("events", []):
                inst = self._deserialize_saved_instance(ev_payload)
                if inst:
                    try:
                        # Robust handling for events whose __init__ could not be executed (missing required args like 'tile').
                        # If the event instance lacks a 'tile' attribute entirely, attempt re-instantiation supplying player & tile.
                        if not hasattr(inst, "tile"):
                            try:
                                cls = inst.__class__
                                sig = inspect.signature(cls.__init__)
                                params = sig.parameters
                                init_kwargs = {}
                                if "player" in params:
                                    init_kwargs["player"] = player
                                if "tile" in params:
                                    init_kwargs["tile"] = tile_instance
                                if "params" in params:
                                    init_kwargs["params"] = None
                                if "repeat" in params:
                                    init_kwargs["repeat"] = False
                                if "name" in params:
                                    # Preserve existing name attribute if any, else class name
                                    init_kwargs["name"] = getattr(
                                        inst, "name", cls.__name__
                                    )
                                reinited = cls(**init_kwargs)
                                inst = reinited
                            except Exception:
                                # Fallback: synthesize minimal attributes
                                try:
                                    inst.player = player
                                except Exception:
                                    pass
                                try:
                                    inst.tile = tile_instance
                                except Exception:
                                    pass
                        # If 'tile' exists but is None, assign it now.
                        if (
                            hasattr(inst, "tile")
                            and getattr(inst, "tile", None) is None
                        ):
                            inst.tile = tile_instance
                        # Always ensure player reference if attribute exists or expected by common pattern.
                        if hasattr(inst, "player"):
                            inst.player = player
                        tile_instance.events_here.append(inst)
                    except Exception:
                        pass
            # items
            for it_payload in tile_data.get("items", []):
                inst = self._deserialize_saved_instance(it_payload)
                if inst:
                    if hasattr(inst, "player"):
                        inst.player = player
                    # Only assign tile if attribute exists and is currently None
                    try:
                        if (
                            hasattr(inst, "tile")
                            and getattr(inst, "tile", None) is None
                        ):
                            inst.tile = tile_instance
                    except Exception:
                        pass
                    tile_instance.items_here.append(inst)
            # npcs
            for npc_payload in tile_data.get("npcs", []):
                inst = self._deserialize_saved_instance(npc_payload)
                if inst:
                    if hasattr(inst, "player"):
                        inst.player = player
                    # Ensure NPCs know which room they occupy. Some NPC classes expect 'current_room',
                    # others may use 'tile'. Set whichever attribute exists and is None so deserialized merchants
                    # have their current_room populated without overwriting an existing reference.
                    try:
                        if (
                            hasattr(inst, "current_room")
                            and getattr(inst, "current_room", None) is None
                        ):
                            inst.current_room = tile_instance
                        if (
                            hasattr(inst, "tile")
                            and getattr(inst, "tile", None) is None
                        ):
                            inst.tile = tile_instance
                    except Exception:
                        pass
                    tile_instance.npcs_here.append(inst)
            # objects
            for obj_payload in tile_data.get("objects", []):
                inst = self._deserialize_saved_instance(obj_payload)
                if inst:
                    if hasattr(inst, "player"):
                        inst.player = player
                    # Ensure objects receive a reference to their tile if they expect it, but don't overwrite
                    try:
                        if (
                            hasattr(inst, "tile")
                            and getattr(inst, "tile", None) is None
                        ):
                            inst.tile = tile_instance
                    except Exception:
                        pass
                    tile_instance.objects_here.append(inst)
            this_map[(x, y)] = tile_instance
        self.maps.append(this_map)

    def game_tick_events(self):
        """
        Processes any events that should occur on a game tick.
        A game tick occurs whenever the game loop iterates,
        which is generally whenever the player takes an action.
        """
        # Trigger merchant refresh on multiples of 1000 before incrementing
        if self.game_tick > 0 and self.game_tick % 1000 == 0:
            self.player.refresh_merchants()

        self.game_tick += 1

        # Decay world-persistent states (Poisoned, Slimed, Petrified, Hollowed, Clean, ...)
        # while not in combat; combat beats drain states via the combat loop instead.
        if self.player is not None and not getattr(self.player, "in_combat", False):
            self.player.cycle_states()

        # Re-evaluate map-entry spawner events every tick, including repeat-flagged
        # ones (each event guards its own has_run/repeat state internally).
        self._evaluate_map_entry_spawners(process_repeats=True)

    def _evaluate_map_entry_spawners(self, process_repeats=False):
        """Scan current map for events that expose evaluate_for_map_entry() and trigger them."""
        try:
            current_map = self.player.map
            if not isinstance(current_map, dict):
                return
            for coord, tile in current_map.items():
                if not isinstance(
                    coord, tuple
                ):  # skip non-coordinate entries like 'name'
                    continue
                if tile is None:
                    continue
                # Work on a shallow copy since event list may mutate during iteration
                for ev in list(getattr(tile, "events_here", [])):
                    if hasattr(ev, "evaluate_for_map_entry"):
                        has_run = getattr(ev, "has_run", False)
                        is_repeat = getattr(ev, "repeat", False)
                        if (not has_run) or (process_repeats and is_repeat):
                            try:
                                ev.evaluate_for_map_entry(self.player)
                            except Exception:
                                continue
        except Exception:
            pass

    @staticmethod
    def parse_hidden(setting: str) -> tuple[bool, int]:
        hidden = False
        hfactor = 0

        if "h+" in setting:
            hidden = True
            hfactor = int(setting[2:])

        return hidden, hfactor
